title: Movie2U Documentation
description: Video accessibility enhancement using AWS services
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
baseurl: "/kitchen-sink"
show_downloads: false 